# Generated by Django 4.2.30 on 2026-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='When a reminder was last emitted for this task', null=True),
        ),
    ]
