# Generated by Django 4.2.30 on 2026-09-21 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('preferred_work_start', models.TimeField(default=datetime.time(9, 0))),
                ('preferred_work_end', models.TimeField(default=datetime.time(22, 0))),
                ('sleep_start', models.TimeField(default=datetime.time(23, 0))),
                ('sleep_end', models.TimeField(default=datetime.time(7, 0))),
                ('default_task_duration', models.IntegerField(default=60, help_text='Default task duration in minutes')),
                ('auto_reschedule', models.BooleanField(default=False, help_text='Allow AI to auto-reschedule flexible tasks without confirmation')),
                ('assistant_tone', models.CharField(choices=[('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual')], default='friendly', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
